baseURL = 'https://nudistbeaaach.github.io/'
languageCode = 'en-us'
title = 'Blog de TaylorDeDordogne'
theme = 'hugo-toigian'


[params]
toc = true
comments = true

[params.author]
name = "TaylorDeDordogne"
email = "taylordedordogne@gmail.com"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true

[build]
  writeStats = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']
